### ISSUE TITLE
Mirror option is not working

### ISSUE THREAD

**Issue by i30817** [atanunq/viu#100]
At least for random pngs.

testcase:
```
#! /usr/bin/env python3

from PIL import Image
import subprocess, io

solid_black = Image.new('RGBA', (50,50), (0, 0, 0, 255))
solid_red = Image.new('RGBA', (50,50), (255, 0, 0, 255))

combined = Image.new('RGBA', (100, 50))
combined.paste(solid_black, box=(0,0))
combined.paste(solid_red, box=(solid_black.size[0],0))

#for comparasion, original
combined.show()
#for bug view
with io.BytesIO() as f:
    combined.save(f, format='png')
    #supposed to be reversed
    subprocess.run(['viu', '-m', '-'], input=f.getbuffer())
```

**Comment by atanunq** [comment]
Yeah, apparently it had been unused for a while. Apologies for the confusion. I removed any references to it in https://github.com/atanunq/viu/commit/15f9f00356275ff212ff98b2d30af8c3a761c74f but that's still not in a tagged version

**Comment by deathtrip** [comment]
Why remove it, instead of fixing?
I think it's a cool feature.

**Comment by i30817** [comment]
It has little point to be. Like i've shown in the code above, if you have 'the bare minimum' of knowhow, you can do it manually then pass to viu anyway.
