### ISSUE TITLE
flaky gif playback

### ISSUE THREAD

**Issue by petabyteboy** [atanunq/viu#12]
Played back with viu: https://img.pbb.lc/id/q69TMdzAWZZiOFQw
Original gif: https://img.pbb.lc/id/ghZl9nche3lymRtv

**Comment by atanunq** [comment]
Thank you for reporting it. I am aware some gifs behave like this, but I still have not figured out the correct way to decode and print them. [This](https://media.giphy.com/media/13gvXfEVlxQjDO/giphy.gif) is another example. I will investigate once I have the time to do so.

**Comment by petabyteboy** [comment]
I think in some cases every frame is only an incremental update to the last one. The pixels that are left out while drawing should actually be drawn in the same color as in the last frame.
