### ISSUE TITLE
implement sixel for higher resolution

### ISSUE THREAD

**Issue by sivizius** [atanunq/viu#16]
with [sixel](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Sixel-Graphics), you can get better resolutions of images.

**Comment by jarun** [comment]
I would suggest use sixel only if it's detected, else use the current method. Most terminal don't have support for sixel today and doesn't work when used with most terminal multiplexers (I am not sure if there's a hack for that but it's not straight).

**Comment by atanunq** [comment]
The tracking issue is now [in `viuer`](https://github.com/atanunq/viuer/issues/4).

**Comment by atanunq** [comment]
Only 20 months later, sixel is now available on master behind a feature flag!

**Comment by AndydeCleyre** [comment]
How can I force or debug sixel usage? I'm trying to test tmux compiled with sixel support, and have installed viu with `cargo install --features sixel viu`, but it's using blocks output.

**Comment by AndydeCleyre** [comment]
Ah, I found this in viuer:

```rust
  fn check_sixel_support() -> bool {
      if let Ok(term) = std::env::var("TERM") {
          match term.as_str() {
              "mlterm" | "yaft-256color" | "foot" | "foot-extra" => return true,
              "st-256color" | "xterm" | "xterm-256color" => {
                  return check_device_attrs().unwrap_or(false)
              }
              _ => {
                  if let Ok(term_program) = std::env::var("TERM_PROGRAM") {
                      return term_program == "MacTerm";
                  }
              }
          }
      }
      false
  }
```

So it works if I preface `viu` with `TERM=foot` or similar. FWIW I'm using wezterm with tmux, and my usual `TERM` is `tmux-256color`.
