### ISSUE TITLE
Directory support

### ISSUE THREAD

**Issue by jarun** [atanunq/viu#21]
Please extend the positional argument FILE to accept a directory as well. It would be great if `viu` could detect the images in the directory and render them.

**Comment by atanunq** [comment]
Thanks for the suggestion, that sounds like a nice thing to have. 
However, how do you think this should work? If it is a directory just print them all as if it had the `-n` parameter? Or do you have something else in mind?

**Comment by jarun** [comment]
> If it is a directory just print them all as if it had the -n parameter?

I think honoring the current program options and printing all the images in the directory should be good enough.

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
@atanunq hope you are safe and doing good.

I have another improvement suggestion for your consideration which would also add a basic image manager framework to `viu`. (I looked for a terminal image manager but couldn't find any)

Can we have an _interactive mode_ in which viu can _page through_ the thumbnails of the images in the directory and wait for user input at a prompt (after each page)?

So, _if each file name is printed along with the index numbers_, users can do certain operations with the files. For example, one can enter `r 5` to rename the file with index number 5 to something else.

What do you think?

**Comment by atanunq** [comment]
Hi. Yes, thank you. I hope you are well, too!

I was thinking of doing something similar when I started this project. However, I wanted to keep things simple back then. Now it sounds like an awesome feature which would be interesting to implement. Although I am currently quite busy and cannot embark on this journey, I will take note.

Thanks for the suggestion!

**Comment by jarun** [comment]
Thank you!
