### ISSUE TITLE
Fish Prompt?

### ISSUE THREAD

**Issue by BarryMode** [atanunq/viu#28]
First of all, viu is super cool. Thank you for making it.

I would just contact you, but I don't see a way to do that from your profile so I thought I'd drop this here:

**Do you mind sharing your fish prompt / color scheme? I really like your shell!**

**Comment by atanunq** [comment]
Hi! I am really happy you like it.

I am afraid that I do not know what exactly my color scheme is. I have been experimenting with
- [kitty](https://github.com/kovidgoyal/kitty)
- [this amazing tmux config](https://github.com/gpakosz/.tmux) and
- [this great plugin for fish](https://github.com/oh-my-fish/theme-bobthefish)

In the end it all fit together and I left it as it was. Now I struggle to collect all the config pieces in one `dotfiles` repository...

For now, all I know is that for `fish` I use `terminal2-light` from [here](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md).
I hope that's helpful.

**Comment by BarryMode** [comment]
Thanks for sharing all that!
