### ISSUE TITLE
Mac patch is successful - not a bug

### ISSUE THREAD

**Issue by CaspianA1** [atanunq/viu#34]
Thanks for reporting! Debugging on Mac has been on my todo list for a while. I will try to get my hands on one soon.

_Originally posted by @atanunq in https://github.com/atanunq/viu/issues/33#issuecomment-596536509_

**Comment by CaspianA1** [comment]
I wasn't sure how to contact you - but just wanted to tell you that it works great on Mac. It's a pleasure to use!

**Comment by atanunq** [comment]
Awesome, thanks for the feedback. And in the future, you could comment on the other, older issues. I get a notification anyway :slightly_smiling_face:

**Comment by CaspianA1** [comment]
Got it

Caspian
