### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by petabyteboy** [atanunq/viu#40]
Hi,
while packaging the new version I noticed the following tests failing:

```
   Compiling viu v1.0.0 (/build/source)
    Finished test [unoptimized + debuginfo] target(s) in 19.97s
     Running target/debug/deps/viu-d487dde3f281252d

running 12 tests

test printer::test::test_ansi_color_from_pixel ... ok
test printer::test::test_buffer_full ... ok
test printer::test::test_get_ansi_transparency_color ... ok
test printer::test::test_get_transparency_color ... ok
test printer::test::test_print_buffer ... ok
test printer::test::test_color_from_pixel ... ok
test term::tests::test_truecolor ... ok
test app::test::test_resize_with_none ... FAILED
test app::test::test_view_without_extension ... FAILED
test app::test::test_resize_only_height ... ok
test app::test::test_resize_given_both ... ok
test app::test::test_resize_only_width ... ok

failures:

---- app::test::test_resize_with_none stdout ----
thread 'app::test::test_resize_with_none' panicked at 'attempt to subtract with overflow', src/app.rs:294:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- app::test::test_view_without_extension stdout ----
thread 'app::test::test_view_without_extension' panicked at 'attempt to subtract with overflow', src/app.rs:294:31


failures:
    app::test::test_resize_with_none
    app::test::test_view_without_extension

test result: FAILED. 10 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--bin viu'
```

Do you think this is related to my environment or can you reproduce it?

**Comment by atanunq** [comment]
Hi, thank you for reporting!

Now I realize that my tests need a serious refactor, they are quite useless.
However, I cannot reproduce it. The error at [line 294](https://github.com/atanunq/viu/blob/587f7aa2583901d02662438becec4aa8c8953933/src/app.rs#L294) leads to the call of [`crossterm::terminal::size()`](https://github.com/atanunq/viu/blob/587f7aa2583901d02662438becec4aa8c8953933/src/app.rs#L283). These two tests are the only ones that trigger the call, hence I assume it is the one failing. What version is `crossterm` was used for building? `grep crossterm Cargo.lock` should do it.
Also running the tests with `RUST_BACKTRACE=1` as per the command output will be helpful, too.

**Comment by atanunq** [comment]
Feel free to reopen if there is something I can do on my side.
