### ISSUE TITLE
Not work in windows

### ISSUE THREAD

**Issue by longwusha** [atanunq/viu#5]
Something below can not build in windows, I am trying to reimplement it with crossterm.

1. libc::ioctl
2. libc::SIGPIPE
3. libc::SIG_DFL

**Comment by atanunq** [comment]
Thanks for looking into it. You might find #2 useful.

**Comment by atanunq** [comment]
Hey, @longwusha, It has been a while but I think the project now builds fine on windows. Do you think you can have a look and see if there is anything outstanding?
