### ISSUE TITLE
Cargo.lock is not up-to-date in 1.2 release

### ISSUE THREAD

**Issue by wezm** [atanunq/viu#51]
It's not possible to build `viu` with `cargo build --release --locked` using the code published as 1.2:

```
error: the lock file /home/wmoore/Projects/aur/viu/src/viu-1.2/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

`cargo build --release --locked` is how the AUR package is built as it ensures that only the version of dependencies specified by the lock file is used, ensuring the build continues to build over time.

The issue seems to be the version was bumped in the `Cargo.toml` but the regenerated `Cargo.lock` was not committed:

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 2a30ef1..1789009 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -861,7 +861,7 @@ checksum = "f1bddf1187be692e79c5ffeab891132dfb0f236ed36a43c7ed39f1165ee20191"

 [[package]]
 name = "viu"
-version = "1.1.0"
+version = "1.2.0"
 dependencies = [
  "clap",
  "crossterm",
```

Would be great if you could publish a patch release with an updated `Cargo.lock`.

**Comment by atanunq** [comment]
Thanks for letting me know! I just pushed `v1.2.1` to address this.

Please shout if there are any more issues!

**Comment by atanunq** [comment]
Can we close this?

**Comment by wezm** [comment]
Yep
