### ISSUE TITLE
Ongoing PR to use viu image backend in neofetch

### ISSUE THREAD

**Issue by oknozor** [atanunq/viu#52]
I thought you might be interested : 

https://github.com/dylanaraps/neofetch/pull/1592 

Thank you for the hard work, I can now display image in neofetch under alacritty/wayland, thanks to you !

**Comment by atanunq** [comment]
That's amazing! Thanks for introducing it to neofetch 🚀

**Comment by atanunq** [comment]
Yay, merged!
