### ISSUE TITLE
No precompiled binary available

### ISSUE THREAD

**Issue by dashavoo** [atanunq/viu#54]
Apologies if I am being really dense here. There are no precompiled binaries in the release page, despite what the README says.
There is a signature, and two source archives.

![image](https://user-images.githubusercontent.com/3750013/99147895-50e64300-267c-11eb-8773-e292bf538dec.png)

**Comment by atanunq** [comment]
Thanks for pointing out! I should make a checklist to make sure I don't miss anything release-related next time.

**Comment by atanunq** [comment]
Fixed with latest release.

**Comment by shilangyu** [comment]
Perhaps setup the CI to create and release artefacts automatically? I can help with that if you want

**Comment by atanunq** [comment]
Thanks for offering. Do you think you can point me where I can have a look at such a setup? Not sure if it's worth the effort at this time with such irregular releases, but it might come in handy.

**Comment by shilangyu** [comment]
Sorry for a late answer.

You are probably right, it might not be worth the effort. Here is an example workflow that compiles for the major platforms and releases them: https://github.com/ajeetdsouza/zoxide/blob/master/.github/workflows/release.yml
