### ISSUE TITLE
maintain aspect ratio when -w and -h are supplied

### ISSUE THREAD

**Issue by Jab2870** [atanunq/viu#55]
Hi, I'd like to be able to print an image to the terminal that maintains aspect ratio that is, say 100 characters tall or wide, whichever is larger.

Is this something you'd consider implementing?

**Comment by atanunq** [comment]
Hi!
Unfortunately, to me this sounds like a pretty niche requirement. Also, IMO, the current behaviour is more intuitive and doing something like this would hurt the UX.
Do you think you can solve the issue on your side? Get the image's dimensions and do a check to figure out on which axis to scale? Then you can use either `-w` or `-h`, but not both.

**Comment by atanunq** [comment]
Please feel free to reopen if you think there should be changes on `viu`'s side.

**Comment by raldone01** [comment]
I used [tiv](https://github.com/radare/tiv) in the past. I now wanted to optionally support viu.
In tiv -h -w are max height/max width. Which is usually what you want.

My use case:
I use tiv and viu in my fish_greeting function on all my linux machines (shell script).

Image using tiv:
![image](https://user-images.githubusercontent.com/27293675/182028273-b9edb726-e546-4279-9508-d4aaef672fa9.png)

Same image using viu:
![image](https://user-images.githubusercontent.com/27293675/182028363-d126fe5e-c446-48f4-b759-a57892aaf1c7.png)

I don't think changing the behaviour would be an issue for many users.
To avoid doing a breaking change I would suggest adding a --fit option that changes the behaviour to make -h and -w max measurements instead.
