### ISSUE TITLE
viu packed for NetBSD

### ISSUE THREAD

**Issue by voidpin** [atanunq/viu#56]
FYI,

I've just packaged and merged `viu` in pkgsrc-current, https://mail-index.netbsd.org/pkgsrc-changes/2020/11/23/msg224315.html

This means that `viu` is now available for all NetBSD users.

Regrads

**Comment by atanunq** [comment]
Nice, thank you! Will make sure to update the readme.

**Comment by voidpin** [comment]
@atanunq thanks, it works perfectly on `kitty`.
Closing this issue now. Cheers
