### ISSUE TITLE
Aspect ratio off on iTerm2

### ISSUE THREAD

**Issue by thorlucas** [atanunq/viu#65]
I've `curl https://via.placeholder.com/20 -o 20.png` to product a 20x20 png. Then I run `viu 20.png` in iTerm2.

Here are the results:

<img width="247" alt="Screen Shot 2021-03-13 at 4 23 01 PM" src="https://user-images.githubusercontent.com/25698466/111053416-6431d100-8418-11eb-9b0f-1d4eb112dd46.png">

As you can see the aspect ratio is clearly off. I suppose this has something to do line height setting? Does iTerm2 have API for polling this?

**Comment by thorlucas** [comment]
According to [iterm2](https://iterm2.com/documentation-images.html), `preserveAspectRatio` should be set to `1` to avoid this.

**Comment by thorlucas** [comment]
P.S. [`imgcat`](https://github.com/eddieantonio/imgcat) has the proper aspect ratio in iTerm2.

**Comment by thorlucas** [comment]
Ok I did some investigation. `imgcat`'s source:

```bash
function print_image() {
    print_osc
    printf '1337;File='
    if [[ -n $1 ]]; then
        printf "name=%s;" "$(printf "%s" "$1" | b64_encode)"
    fi

    printf "%s" "$3" | b64_decode | wc -c | awk '{printf "size=%d",$1}'
    printf ";inline=%s" "$2"
    printf ":"
    printf "%s" "$3"
    print_st
    printf '\n'
    if [[ -n $4 ]]; then
        echo "$1"
    fi
}
```

Which evaluates to 

`\033]1337;File=size=165;inline=1:<the base64 encoded image>\a`

**Comment by atanunq** [comment]
Followed up in the linked `viuer` issue.
