### ISSUE TITLE
Support wezterm

### ISSUE THREAD

**Issue by forivall** [atanunq/viu#72]
[it supports the iTerm protocol](https://github.com/wez/wezterm/blob/main/docs/imgcat.md)

**Comment by kidonng** [comment]
You can just [fake it as iTerm](https://github.com/atanunq/viuer/blob/a9e638cce13f1012bc64e6ce33a848ac461675c3/src/printer/iterm.rs#L90) for the moment:

```sh
export TERM_PROGRAM = iTerm
viu ...
```

**Comment by atanunq** [comment]
https://github.com/atanunq/viuer/issues/26#issuecomment-907796274
