### ISSUE TITLE
Webp images are displayed without colors

### ISSUE THREAD

**Issue by kidonng** [atanunq/viu#73]
Running viu 8a2324a94cb1e53511094f2675b9c27ea7e273d4 with kitty 0.20.3, on macOS 11.4. JPG/PNG images doesn't have this problem. Is this a issue with viu itself or `image` library?

![image](https://user-images.githubusercontent.com/44045911/117991195-678dfe00-b370-11eb-9a26-5b3eebb1d87c.png)

**Comment by atanunq** [comment]
Hey! Sorry for the massive delay, but yes, looks like a feature that is not yet implemented, [link](https://github.com/image-rs/image/blob/7d280f5745fcbd1c8af819b265dc81b63cacd6b4/src/codecs/webp/decoder.rs#L51-L52).

**Comment by kidonng** [comment]
Works now :tada:
