### ISSUE TITLE
Add package to homebrew

### ISSUE THREAD

**Issue by ShivamJoker** [atanunq/viu#79]
Hey it would be great if we can get this package using brew as well rather than compiling from sources.

**Comment by simonSlamka** [comment]
+1 definitely would help

**Comment by alebcay** [comment]
Hello, I've opened https://github.com/Homebrew/homebrew-core/pull/85164 to get `viu` added to the Homebrew core repo.

**Comment by alebcay** [comment]
`viu` is now available via Homebrew on macOS and Linux with `brew install viu` - details at https://formulae.brew.sh/formula/viu.

**Comment by ShivamJoker** [comment]
Thats perfect thanks :)

**Comment by atanunq** [comment]
Thank you very much, @alebcay! I'll make sure to put it in the readme
