### ISSUE TITLE
KDE Konsole

### ISSUE THREAD

**Issue by niksingh710** [atanunq/viu#82]
I am using Kubuntu and the default terminal that is Konsole.
and I installed viu via cargo
The image shown is pixelated.

Version
viu = 1.3.0
konsole = 21.08.1

Is there any way to resolve it?

**Comment by atanunq** [comment]
afaik, Konsole does not support any of the image-displaying protocols that `viu` supports (kitty, iterm and sixel). Hence, it falls back to the default block-based display. See [demo](https://github.com/atanunq/viu/blob/master/img/demo.gif) from readme.

If you are eager to try it out, you can use it on a different terminal emulator, like Kitty.

**Comment by SaltyKitkat** [comment]
I'm using konsole 22.12.1 and it support sixel now.

However, it seems that viu-1.4.0 still using block-based display on konsole. I don't know why but lsix seems working well with konsole.

**Comment by niksingh710** [comment]
> I'm using konsole 22.12.1 and it support sixel now.
> 
> However, it seems that viu-1.4.0 still using block-based display on konsole. I don't know why but lsix seems working well with konsole.

Use chafa with `chafa -f sixel /path/to/img.png`
