### ISSUE TITLE
Images get blurred out

### ISSUE THREAD

**Issue by Enforcer007** [atanunq/viu#83]
Thanks for the tool. 

I see the images are getting blurred out. Please see below the screenshots.

![viu_screenshot](https://user-images.githubusercontent.com/6951100/133391565-2cfba7bb-8400-42b9-969a-1681049f8ac0.png)

The original Image:
![image](https://user-images.githubusercontent.com/6951100/133391627-a0058b40-43f5-4548-b9d6-a5d7c50ee977.jpg)

Below are the properties of image and system:

Width x Height = 897 x 898 pixels
Size = 341.3 kb
format = jpeg

----------------------

Terminal = GNOME Terminal 
OS = Ubuntu 20.04

**Comment by atanunq** [comment]
This is a feature 🙂 
On terminal emulators that do not support any of the special image-displaying features, `viu` falls back to simple block-based printing that works in most places. You will be able to see the images in full resolution if you use a different emulator, like Kitty or iTerm. The readme has more information about the supported protocols.

**Comment by gerrywastaken** [comment]
The associated code:
https://github.com/atanunq/viu/blob/2515f667eef5560d04e4693a5e4d0a8e9a801976/src/app.rs#L158-L173
