### ISSUE TITLE
Use sixel on foot

### ISSUE THREAD

**Issue by crabvk** [atanunq/viu#86]
Viu displays images in [foot](https://codeberg.org/dnkl/foot) using half blocks while foot has support for sixel images.

**Comment by atanunq** [comment]
Hello! Have you compiled the binary with the `sixel` feature enabled? Can you also make sure your `$TERM` is `foot` or `foot-extra`? Besides that, the sixel support is in very early alpha and could use a lot of improvements...

**Comment by crabvk** [comment]
Oops, viu was compiled without sixel feature. Thank you.
