### ISSUE TITLE
Sixel support not mentioned in readme

### ISSUE THREAD

**Issue by vilcans** [atanunq/viu#91]
I first dismissed viu because it seemed to not be able to output the Sixel format that the MSYS2 terminal supports.

But then I discovered that it was behind a feature, so to install it with Sixel support, run:

```
cargo install viu --features=sixel
```

All good!👍 But this should be mentioned in the installation instructions.

**Comment by thisismygitrepo** [comment]
this should be opened again, readme is not as obvious as explained here and binaries are missing the feature.

**Comment by zhuconv** [comment]
That's right @thisismygitrepo . I cannot understand how to use sixel with viu in README until seeing this.

**Comment by Rhylan2333** [comment]
Received!
